language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip

install:
  - python -m pip install .

before_script:
  - python -m pip install nose coverage codecov flake8
  - python -m pip install numpy scipy pillow

script:
  - flake8 .
  - nosetests --nologcapture -a '!slow' --with-coverage --cover-package kombine

after_success:
  - codecov
